CREATE DATABASE Academy1



USE Academy1

CREATE TABLE Curators
(
Id INT IDENTITY(1,1) PRIMARY KEY,
Firstname NVARCHAR(MAX) NOT NULL CHECK(Firstname <>'') ,
Lastname NVARCHAR(MAX) NOT NULL CHECK(Lastname <>'') 
)

CREATE TABLE Faculties 
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Financing MONEY NOT NULL CHECK(Financing >= 0) Default 0,
Name NVARCHAR(100) NOT NULL CHECK(Name <>'') Unique
)

CREATE TABLE Departments(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Financing MONEY NOT NULL CHECK(Financing >= 0) Default 0,
Name NVARCHAR(100) NOT NULL CHECK(Name <>'') Unique,
FacultyId INT NOT NULL FOREIGN KEY REFERENCES Faculties(Id)
)



CREATE TABLE Groups
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(10) NOT NULL CHECK(NAME<>'') UNIQUE,
Year INT NOT NULL CHECK (Year between 1 and 5),
DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments(Id)
)


CREATE TABLE GroupsCurators(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CuratorId INT NOT NULL FOREIGN KEY REFERENCES Curators(Id),
GroupId INT NOT NULL FOREIGN KEY REFERENCES Groups(Id)
)
CREATE TABLE Subjects(
Id INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
Name NVARCHAR(100) NOT NULL CHECK(Name <>'') UNIQUE
)

CREATE TABLE Teachers(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(MAX) NOT NULL CHECK(Name <>''),
Surname NVARCHAR(MAX) NOT NULL CHECK(SURNAME<>''),
Salary MONEY NOT NULL CHECK(Salary>0)
)

CREATE TABLE Lectures(
Id INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
LectureRoom NVARCHAR(MAX) NOT NULL CHECK(LectureRoom<>''),
SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id),
TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
)


CREATE TABLE GroupsLectures
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
GroupId INT NOT NULL FOREIGN KEY REFERENCES Groups(Id),
LectureId INT NOT NULL FOREIGN KEY REFERENCES  Lectures(Id)
)





